In [14]:
import numpy as np
import pandas as pd
import math
import random
if __name__ == '__main__':
    np.random.seed(0)
    df = pd.DataFrame(100 + np.random.randn(100).cumsum(), columns=['weight'])
    df['pct_change'] = df.weight.pct_change()
    df['w_log'] = np.log(np.asarray(df['weight']+2 , dtype=float))
import sys
sys.setrecursionlimit(999999999) 
import copy
import os

# Programming Assignment #1

In [20]:
n1=np.array(3141592653589793238462643383279502884197169399375105820974944592)
n2=np.array(2718281828459045235360287471352662497757247093699959574966967627)
n1*n2

8539734222673567065463550869546574495034888535765114961879601127067743044893204848617875072216249073013374895871952806582723184

In [21]:
def Karatsuba(n1,n2):
    if n1>9 and n2>9:
        len1=int(math.log10(n1)+1)
        len2=int(math.log10(n2)+1)
        cuti1=int(len1/2)
        cuti2=int(len2/2)
        a=int(str(n1)[:cuti1])
        b=int(str(n1)[cuti1:])
        c=int(str(n2)[:cuti2])
        d=int(str(n2)[cuti2:])
        out=10**(len1+len2-cuti1-cuti2)*Karatsuba(a,c)+10**(cuti1)*(Karatsuba((a+b),(c+d))-Karatsuba(a,c)-Karatsuba(b,d))+Karatsuba(b,d)  
    else:
#         print(n1)
#         print(n2)
        out=n1*n2
    return out

In [22]:
Karatsuba(n1,n2)

8539733322506366439643181439250694574578804738021548360519171792759034088638461158497275374446565447587786330443409605606163184

In [23]:
def cutintopairs(a):
    # 功能就是把整个数据切开成若干
    astr=str(a)
    lena=np.array(int(math.log10(a))+1)
    aout=np.zeros([lena])
    for i in range(lena):
        aout[i]= astr[i]
    return aout

# Programming Assignment #2

In [24]:
objectarray=np.loadtxt('Programming Assignment #2.txt')
len(objectarray)
objectarray

array([54044., 14108., 79294., ..., 74018., 71187., 91901.])

In [25]:
def mergesort(a,b):
    lena=len(a)
    out=np.zeros(len(a)*2)
    i=0
    j=0
    k=0
    while k < (lena*2):


#         print(a[i])
#         print(b[j])
        if a[i]<b[j]:
            out[k]=a[i]
            i=i+1
        else:
            out[k]=b[j]
            j=j+1
        k=k+1

        if i== len(a):
            out[k:]=b[j:]
            k=(lena*2)
        if j== len(b):
            out[k:]=a[i:]
            k=(lena*2)
#         print(out)
    return out
a=np.array([1,5])
b=np.array([2,8])       
print(mergesort(a,b))
            
        
        
        
        

[1. 2. 5. 8.]


In [26]:
def mergecount(a,b):
   # ab 判断第一个数字的大小，小的在前面,要求ab是两个排序好的数组
#     if a[0]>b[0]:
#         tem=a
#         a=b
#         b=tem
    lena=len(a)
    out=np.zeros(len(a)+len(b))
    i=0
    j=0
    k=0
    splitinv=0
    while k < (lena*2):
#         print(a[i])
#         print(b[j])
        if a[i]<b[j]:
            out[k]=a[i]
            i=i+1
        else:
            out[k]=b[j]
            splitinv=splitinv+lena-i
    
            j=j+1
        k=k+1

        if i== len(a):
            out[k:]=b[j:]
            k=(lena*2)
        if j== len(b):
            out[k:]=a[i:]
            k=(lena*2)
#         print(out)
    return out,splitinv
a=np.array([1,4,5])
b=np.array([2,3,8])        
print(mergecount(a,b))

(array([1., 2., 3., 4., 5., 8.]), 4)


In [27]:
 def sortcount(array):
    if len(array)==0 or len(array)==1:
        return array,0
    else:
        a=array[:int(len(array)/2)]
        b=array[int(len(array)/2):]
#         print(b)
#         print(int(len(array)/2))
        c,leftinv=sortcount(a)
        d,rightinv=sortcount(b)
        out,splitinv=mergecount(c,d)
        invsum=leftinv+rightinv+splitinv
#         print(leftinv)
#         print(rightinv)
#         print(splitinv)
        return(out,invsum)
a=np.array([1,5,2,3,8,7])
# a=np.array([1,8,7])
print(sortcount(a))

(array([1., 2., 3., 5., 7., 8.]), 3)


In [28]:
out,inv=sortcount(objectarray)
inv

2407905288

In [29]:
len(objectarray)

100000

# Programming Assignment #3

## define  function

In [30]:
def partition(A,l,r):
    #l是起始值0，r是最终值，如len(A)-1
    comparecount=0
    p=A[l]
    i=l+1
    for j in range (i,r+1):#注意如果遍历到最后一个数需要到r+1
#         print(j)

        comparecount=comparecount+1
        if A[j]<p:
            temp=A[i]
            A[i]=A[j]
            A[j]=temp
            i=i+1
    temp=A[l]
    A[l]=A[i-1]
    A[i-1]=temp
    return i-1,A,comparecount
# A=[1,2,5,9,7,8,100,135,11,9999]

In [31]:
def choosepivotfirst(A,l,r):
    return l
def leftquicksort(A,l,r):
    count=0
    if l>=r:
        return A,count
    else:
        i=choosepivotfirst(A,l,r)
#         print(i)
        temp=A[l]
        A[l]=A[i]
        A[i]=temp
        j,A,count1=partition(A,l,r)
#         print(j)
        A,count2=leftquicksort(A,l,j-1)
        A,count3=leftquicksort(A,j+1,r)
        return A,count1+count2+count3

In [32]:
def choosepivotmiddle(A,l,r):
    if (r-l+1) % 2 == 0:
        k=int((r-l+1)/2)-1+l
    else:
        k=int(len(A[l:r])/2)+l
    B=[A[l],A[k],A[r]]
    B,countnouse=leftquicksort(B,0,2)
#     print(B)
    for i in [l,k,r]:
        if A[i]==B[1]:
            out=i
    return out

# test median

def quicksort(A,l,r):
    count=0
    if l>=r:
        return A,count
    else:
        i=choosepivotmiddle(A,l,r)
#         print(i)
#         print(i)
        temp=A[l]
        A[l]=A[i]
        A[i]=temp
        j,A,count1=partition(A,l,r)
#         print(j)

        A,count2=quicksort(A,l,j-1)
        A,count3=quicksort(A,j+1,r)
        return A,count1+count2+count3
# A=objectarray
# print(quicksort(A,0,len(A)-1) )
A=[7, 1, 3, 6, 2, 5, 4, 9, 8]
A[choosepivotmiddle(A,0,len(A)-1)]
A=[4, 1, 3, 6, 2, 5]
A[choosepivotmiddle(A,0,len(A)-1)]

4

In [33]:
def choosepivotfinal(A,l,r):
    return r
def rightquicksort(A,l,r):
#     print(A)
    count=0
    if l>=r:
        return A,count
    else:
        i=choosepivotfinal(A,l,r)
#         print(i)
        temp=A[l]
        A[l]=A[i]
        A[i]=temp
        j,A,count1=partition(A,l,r)
#         print(j)
        A,count2=rightquicksort(A,l,j-1)
        A,count3=rightquicksort(A,j+1,r)
        return A,count1+count2+count3
# print(leftquicksort(A,0,len(A)-1) )
# choosepivotmiddle(A,0,len(A)-1)
# print(rightquicksort(A,0,len(A)-1) )

## test

In [34]:
A=[3,2,1,4,5]  #6 10 6
print(leftquicksort(A,0,len(A)-1) )
A=[3,2,1,4,5]  #6 10 6
print(rightquicksort(A,0,len(A)-1) )
A=[3,2,1,4,5]  #6 10 6
print(quicksort(A,0,len(A)-1) )

([1, 2, 3, 4, 5], 6)
([1, 2, 3, 4, 5], 10)
([1, 2, 3, 4, 5], 6)


In [35]:
A=[1,6,8,10,7,5,2,9,4,3]  #26 21 21
print(leftquicksort(A,0,len(A)-1) )
A=[1,6,8,10,7,5,2,9,4,3]  #26 21 21
print(rightquicksort(A,0,len(A)-1) )
A=[1,6,8,10,7,5,2,9,4,3]  #26 21 21
print(quicksort(A,0,len(A)-1) )

([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 26)
([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 21)
([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 21)


In [44]:
A=np.loadtxt('week3test.txt')# 答案 24308571  25371973  21214423
# print(leftquicksort(A,0,len(A)-1) )
# print(rightquicksort(A,0,len(A)-1) )
print(quicksort(A,0,len(A)-1) )

(array([1.00000e+00, 2.00000e+00, 3.00000e+00, ..., 9.99998e+05,
       9.99999e+05, 1.00000e+06]), 21214423)


## final answer

In [38]:
objectarray=np.loadtxt('Programming Assignment #3.txt')
len(objectarray)
A=objectarray


print(leftquicksort(A,0,len(A)-1) )
#162085

(array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
       1.000e+04]), 162085)


In [41]:
objectarray=np.loadtxt('Programming Assignment #3.txt')
A=objectarray
print(rightquicksort(A,0,len(A)-1) )
#164123

(array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
       1.000e+04]), 164123)


In [45]:
objectarray=np.loadtxt('Programming Assignment #3.txt')
A=objectarray
print(quicksort(objectarray,0,len(objectarray)-1) )
#138382

(array([1.000e+00, 2.000e+00, 3.000e+00, ..., 9.998e+03, 9.999e+03,
       1.000e+04]), 138382)


# Programming Assignment #4

## define functions

In [42]:
def contraction(A,sizeA):
# 输入原始矩阵，只进行一次随机运算，给出来最后还剩下的edge总数
#     print(A)#打印原始数据
#     print('sizeA'+str(sizeA))
    for iteration in range (A.shape[0]-2):#最后只剩两个数
#     for iteration in range (1):
#         print('newloop')
    
        i,j=choose(A)# 选出来任意一个点
#         np.savetxt('Asave.txt',A)
#         print(A[i,j])
        cleanedone=int(A[i,j]-1)# 所选点列号对应的vector删掉，行保留
        retainedone=int(i)
#         print('cleanedone'+str(cleanedone))
#         print('retainedone'+str(retainedone))
        k=1# 把删除的vector连接的所有点合并过去
        while k != A.shape[1]:# 把保留点中所有和clean点的连线都删除
            if A[retainedone,k]==cleanedone+1:
                A[i,k:(A.shape[1]-1)]=A[i,k+1:]
                k=k-1
                sizeA[i]=sizeA[i]-1
            k=k+1
#         print('cleandedA')
#         print(A)
#         print('sizeA'+str(sizeA))
        for it2 in range(1,int(sizeA[cleanedone])):# 每一行第一个数是行号，所以检索的时候也从第二列开始
            if A[cleanedone,it2] != retainedone+1: # cleandedone里面，除了保留点本身的连线不加，其他连线全都合并到保留点里面  ，即便clean点和保留点之前有共同的连线点也要加上， 因为那些连接没有被删除，而是出现在合并点中

                sizeA[retainedone]=sizeA[retainedone]+1

                A[retainedone,int(sizeA[retainedone]-1)]=A[cleanedone,it2]
        A[cleanedone,:]=np.zeros(A.shape[1]) #为了保持行号还是正确的，所以不删除行只是全部清除为0
        sizeA[cleanedone]=0
        A[np.where(A==cleanedone+1)]=retainedone+1#把别的点和被清除点的连线全都改掉
#         print('switchedA'+str(A))
    return sizeA[np.where(sizeA!=0)][0]-1# size本身算了行号
    
def choose(A):
    i=random.randint(0, A.shape[0]-1)
    j=random.randint(1,A.shape[1]-1) #选的时候要跳过行号，否则就是自己和自己配对了
    while A[i,j]==0:
        i=random.randint(0, A.shape[0]-1)
        j=random.randint(1,A.shape[1]-1)
    return i,j


## test_old

In [27]:
lenA=8
A=np.zeros([lenA,lenA*3])
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('/Users/yuta/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/assign4test1.txt',header=None,sep=' ',skiprows=list(range(0,i*2)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#     print(B)
#     print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)

In [26]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(50):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    if minsize>size:
        minsize=size
minsize

4.0
3.0
6.0
1.0
7.0
8.0
4.0
2.0
3.0
6.0
1.0
7.0
5.0
1.0
8.0
2.0
7.0
3.0
2.0
7.0
6.0
1.0
5.0
3.0
1.0
6.0
3.0
2.0
5.0
7.0
5.0
8.0
7.0
1.0
2.0
4.0
3.0
6.0
8.0
2.0
5.0
7.0
2.0
3.0
7.0
6.0
4.0
1.0
1.0
7.0
5.0
4.0
3.0
2.0
6.0
3.0
7.0
5.0
4.0
2.0
1.0
7.0
4.0
2.0
8.0
3.0
8.0
5.0
3.0
6.0
4.0
7.0
1.0
7.0
5.0
2.0
3.0
6.0
7.0
8.0
5.0
1.0
3.0
2.0
3.0
6.0
5.0
1.0
2.0
8.0
1.0
6.0
2.0
4.0
5.0
3.0
3.0
4.0
6.0
1.0
7.0
8.0
5.0
1.0
7.0
6.0
3.0
2.0
1.0
3.0
5.0
6.0
2.0
8.0
2.0
6.0
7.0
8.0
1.0
3.0
2.0
3.0
1.0
5.0
4.0
8.0
6.0
4.0
1.0
3.0
5.0
7.0
7.0
1.0
6.0
5.0
3.0
8.0
5.0
1.0
4.0
6.0
2.0
3.0
1.0
8.0
4.0
6.0
7.0
2.0
2.0
7.0
8.0
1.0
4.0
3.0
5.0
4.0
7.0
3.0
1.0
8.0
2.0
8.0
7.0
1.0
5.0
4.0
7.0
4.0
5.0
3.0
6.0
1.0
3.0
2.0
5.0
4.0
1.0
7.0
3.0
2.0
6.0
1.0
7.0
4.0
4.0
7.0
5.0
8.0
6.0
2.0
1.0
7.0
8.0
2.0
4.0
3.0
3.0
2.0
7.0
8.0
5.0
1.0
2.0
6.0
8.0
1.0
4.0
3.0
2.0
6.0
1.0
4.0
3.0
7.0
5.0
1.0
6.0
8.0
2.0
3.0
1.0
5.0
4.0
2.0
6.0
7.0
7.0
6.0
8.0
5.0
4.0
2.0
7.0
8.0
5.0
4.0
6.0
1.0
1.0
4.0
3.0
8.0
7.0
5.0
2.0
7.0
3.0
1.0


2.0

In [10]:
lenA=40
A=np.zeros([lenA,lenA*3])
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('/Users/yuta/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/assign4test2.txt',header=None,sep=' ',skiprows=list(range(0,i*2)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#     print(B)
#     print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)


In [11]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(50):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    if minsize>size:
        minsize=size
minsize

3.0

In [8]:
lenA=8
A=np.zeros([lenA,lenA*3])
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('assign4test3.txt',header=None,sep=' ',skiprows=list(range(0,i*2)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#     print(B)
#     print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)
C

array([[1., 3., 4., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 1., 4., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 1., 2., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 5., 3., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 4., 8., 6., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [6., 8., 7., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 5., 8., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [8., 5., 7., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(50):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    if minsize>size:
        minsize=size
minsize

1.0

In [10]:
lenA=8
A=np.zeros([lenA,lenA*3])
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('assign4test4.txt',header=None,sep=' ',skiprows=list(range(0,i*2)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#     print(B)
#     print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)
C

array([[1., 2., 3., 4., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 3., 4., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [3., 4., 1., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [4., 1., 2., 3., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 1., 6., 7., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [6., 7., 8., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 8., 5., 6., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [8., 4., 6., 5., 7., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(50):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    if minsize>size:
        minsize=size
minsize

2.0

In [21]:
#answer 22
lenA=100
A=np.zeros([lenA,lenA*20])# *10的长度只是预估的，有可能够用有可能不够用,加满了会在26行报错
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('assign4test5.txt',header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
    B[0,-1]=0
#     print(B)
# print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)
A
# np.savetxt('A.txt',A)

array([[  1.,  15.,  46., ...,   0.,   0.,   0.],
       [  2.,  77.,  52., ...,   0.,   0.,   0.],
       [  3.,   2.,  73., ...,   0.,   0.,   0.],
       ...,
       [ 98.,   1.,   4., ...,   0.,   0.,   0.],
       [ 99.,   2.,   8., ...,   0.,   0.,   0.],
       [100.,   1.,   3., ...,   0.,   0.,   0.]])

In [22]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(20):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    print(size)
    if minsize>size:
        minsize=size
minsize

131.0
52.0
123.0
30.0
30.0
22.0
145.0
34.0
26.0
31.0
158.0
142.0


KeyboardInterrupt: 

In [29]:
#answer 61
lenA=200
A=np.zeros([lenA,int(lenA**2/2)])# *长度如果不够用,加满了会在26行报错，平方后一定是够用的，不过是分配的内存很大了
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('assign4test6.txt',header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
    B[0,-1]=0
#     print(B)
# print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)
A
# np.savetxt('A.txt',A)

array([[  1.,  54., 184., ...,   0.,   0.,   0.],
       [  2.,   1., 100., ...,   0.,   0.,   0.],
       [  3.,   1.,   2., ...,   0.,   0.,   0.],
       ...,
       [198.,   3.,   7., ...,   0.,   0.,   0.],
       [199.,   7.,  10., ...,   0.,   0.,   0.],
       [200.,   6.,   7., ...,   0.,   0.,   0.]])

In [30]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(100):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    print(size)
    if minsize>size:
        minsize=size
minsize

88.0
273.0
68.0
78.0
266.0
61.0
71.0
262.0
272.0
75.0
270.0
63.0
77.0
253.0
299.0
274.0
67.0
72.0
64.0
253.0
67.0
266.0
67.0
75.0
273.0
75.0
270.0
82.0
266.0
274.0
273.0
266.0
89.0
284.0


PermissionError: [Errno 13] Permission denied: 'Asave.txt'

In [15]:
#answer 51
lenA=200
A=np.zeros([lenA,int(lenA**2/2)])# *长度如果不够用,加满了会在26行报错，平方后一定是够用的，不过是分配的内存很大了
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv('assign4test7.txt',header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
    B[0,-1]=0
#     print(B)
# print(B.shape)
    sizeA[i]=B.shape[1]
    A[i,0:B.shape[1]]=B[0,:]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)
A
# np.savetxt('A.txt',A)

array([[  1.,  58.,  90., ...,   0.,   0.,   0.],
       [  2.,  55., 179., ...,   0.,   0.,   0.],
       [  3.,   2., 169., ...,   0.,   0.,   0.],
       ...,
       [198.,   4.,   5., ...,   0.,   0.,   0.],
       [199.,   5.,   6., ...,   0.,   0.,   0.],
       [200.,   4.,   6., ...,   0.,   0.,   0.]])

In [12]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(300):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    print(size)
    if minsize>size:
        minsize=size
minsize

258.0
261.0
63.0
76.0
75.0
262.0
111.0
262.0
71.0
76.0
249.0
365.0
298.0
262.0
277.0
100.0
78.0
261.0
281.0
277.0
63.0
67.0
67.0
257.0
63.0
272.0
249.0
275.0
65.0
104.0
108.0
258.0
66.0
279.0
102.0
64.0
71.0
281.0
277.0
69.0
99.0
249.0
68.0
93.0
92.0
80.0
303.0
78.0
78.0
80.0
277.0
249.0
62.0
62.0
72.0
120.0
78.0
71.0
257.0
81.0
264.0
68.0
257.0
300.0
71.0
66.0
78.0
74.0
277.0
92.0
62.0
66.0
93.0
83.0
299.0
77.0
64.0
79.0
63.0
274.0
81.0
261.0
256.0
258.0
306.0
57.0
76.0
85.0
119.0
93.0
315.0
266.0
82.0
274.0
91.0
276.0
260.0
273.0
82.0
57.0
262.0
66.0
278.0
71.0
57.0
71.0
69.0
106.0
249.0
73.0
277.0
339.0
295.0
299.0
272.0
260.0
78.0
78.0
281.0
64.0
249.0
270.0
71.0
57.0
75.0
273.0
308.0
279.0
67.0
75.0
275.0
257.0
270.0
67.0
278.0
289.0
64.0
267.0
290.0
59.0
261.0
261.0
65.0
67.0
260.0
61.0
71.0
262.0
274.0
112.0
277.0
58.0
264.0
69.0
249.0
249.0
59.0
274.0
65.0
76.0
66.0
118.0
61.0
63.0
62.0
399.0
93.0
261.0
63.0
99.0
257.0
283.0
69.0
64.0
65.0
299.0
67.0
274.0
266.0
74.0
65.0
68.0


57.0

## test new

In [45]:
path='D:/onedrive/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/stanford-algs-master/stanford-algs-master/testCases/course1/assignment4MinCut'
os.chdir(path)
for txtname in os.listdir():
    if len(txtname)==20:
        lenA=6
        A=np.zeros([lenA,int(lenA**2/2)])# *长度如果不够用,加满了会在26行报错，平方后一定是够用的，不过是分配的内存很大了
        sizeA=np.zeros([lenA,1])
        for i in range(lenA):
        #     print(i)
            B=np.array(pd.read_csv(txtname,header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#             B[0,-1]=0
#             print(B)
        # print(B.shape)
            sizeA[i]=B.shape[1]#这样读最后会多读出来一个0
            A[i,0:B.shape[1]]=B[0,:]
        C=copy.deepcopy(A)
        sizeC=copy.deepcopy(sizeA)
        A=copy.deepcopy(C)
        sizeA=copy.deepcopy(sizeC)
        minsize=contraction(A,sizeA)
        for i in range(lenA*10):
            A=copy.deepcopy(C)
            sizeA=copy.deepcopy(sizeC)
            size=contraction(A,sizeA)
            if minsize>size:
                minsize=size
        print(txtname+'calculated:'+str(minsize))
        txtname2='output'+txtname[5:]
#         txtname2[:5]=
        answer=np.loadtxt(path+'/'+txtname2)
        print(txtname2+'answer:'+str(answer))



input_random_1_6.txtcalculated:2.0
output_random_1_6.txtanswer:2.0
input_random_2_6.txtcalculated:1.0
output_random_2_6.txtanswer:1.0
input_random_3_6.txtcalculated:3.0
output_random_3_6.txtanswer:3.0
input_random_4_6.txtcalculated:4.0
output_random_4_6.txtanswer:4.0


In [46]:
path='D:/onedrive/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/stanford-algs-master/stanford-algs-master/testCases/course1/assignment4MinCut'
os.chdir(path)
for txtname in os.listdir():
    if len(txtname)==21 and txtname[-5] == '0':
        lenA=10
        A=np.zeros([lenA,int(lenA**2/2)])# *长度如果不够用,加满了会在26行报错，平方后一定是够用的，不过是分配的内存很大了
        sizeA=np.zeros([lenA,1])
        for i in range(lenA):
        #     print(i)
            B=np.array(pd.read_csv(txtname,header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#             B[0,-1]=0
#             print(B)
        # print(B.shape)
            sizeA[i]=B.shape[1]#这样读最后会多读出来一个0
            A[i,0:B.shape[1]]=B[0,:]
        C=copy.deepcopy(A)
        sizeC=copy.deepcopy(sizeA)
        A=copy.deepcopy(C)
        sizeA=copy.deepcopy(sizeC)
        minsize=contraction(A,sizeA)
        for i in range(lenA*10):
            A=copy.deepcopy(C)
            sizeA=copy.deepcopy(sizeC)
            size=contraction(A,sizeA)
            if minsize>size:
                minsize=size
        print(txtname+'calculated:'+str(minsize))
        txtname2='output'+txtname[5:]
#         txtname2[:5]=
        answer=np.loadtxt(path+'/'+txtname2)
        print(txtname2+'answer:'+str(answer))



input_random_5_10.txtcalculated:4.0
output_random_5_10.txtanswer:4.0
input_random_6_10.txtcalculated:3.0
output_random_6_10.txtanswer:3.0
input_random_7_10.txtcalculated:2.0
output_random_7_10.txtanswer:2.0
input_random_8_10.txtcalculated:1.0
output_random_8_10.txtanswer:1.0


In [ ]:
path='D:/onedrive/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/stanford-algs-master/stanford-algs-master/testCases/course1/assignment4MinCut'
os.chdir(path)
for txtname in os.listdir():
    if len(txtname)==23 and txtname[-7] == '1':
        lenA=200
        A=np.zeros([lenA,int(lenA**2/2)])# *长度如果不够用,加满了会在26行报错，平方后一定是够用的，不过是分配的内存很大了
        sizeA=np.zeros([lenA,1])
        for i in range(lenA):
        #     print(i)
            B=np.array(pd.read_csv(txtname,header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#             B[0,-1]=0
#             print(B)
        # print(B.shape)
            sizeA[i]=B.shape[1]#这样读最后会多读出来一个0
            A[i,0:B.shape[1]]=B[0,:]
        C=copy.deepcopy(A)
        sizeC=copy.deepcopy(sizeA)
        A=copy.deepcopy(C)
        sizeA=copy.deepcopy(sizeC)
        minsize=contraction(A,sizeA)
        for i in range(lenA*10):
            A=copy.deepcopy(C)
            sizeA=copy.deepcopy(sizeC)
            size=contraction(A,sizeA)
            if minsize>size:
                minsize=size
        print(txtname+'calculated:'+str(minsize))
        txtname2='output'+txtname[5:]
#         txtname2[:5]=
        answer=np.loadtxt(path+'/'+txtname2)
        print(txtname2+'answer:'+str(answer))



### 调试：先用最小的case，而且打印出每一小歩的结果一项一项比较就能找到问题

In [37]:
def contraction(A,sizeA):
# 输入原始矩阵，只进行一次随机运算，给出来最后还剩下的edge总数
    print(A)#打印原始数据
    print('sizeA'+str(sizeA))
    for iteration in range (A.shape[0]-2):#最后只剩两个数
#     for iteration in range (1):
        print('newloop')
    
        i,j=choose(A)# 选出来任意一个点
#         np.savetxt('Asave.txt',A)
#         print(A[i,j])
        cleanedone=int(A[i,j]-1)# 所选点列号对应的vector删掉，行保留
        retainedone=int(i)
        print('cleanedone'+str(cleanedone))
        print('retainedone'+str(retainedone))
        k=1# 把删除的vector连接的所有点合并过去
        while k != A.shape[1]:# 把保留点中所有和clean点的连线都删除
            if A[retainedone,k]==cleanedone+1:
                A[i,k:(A.shape[1]-1)]=A[i,k+1:]
                k=k-1
                sizeA[i]=sizeA[i]-1
            k=k+1
        print('cleandedA')
        print(A)
        print('sizeA'+str(sizeA))
        for it2 in range(1,int(sizeA[cleanedone])):# 每一行第一个数是行号，所以检索的时候也从第二列开始
            if A[cleanedone,it2] != retainedone+1: # cleandedone里面，除了保留点本身的连线不加，其他连线全都合并到保留点里面  ，即便clean点和保留点之前有共同的连线点也要加上， 因为那些连接没有被删除，而是出现在合并点中
#                print(A[cleanedone,it2])
                sizeA[retainedone]=sizeA[retainedone]+1
#                 print(sizeA)
#                 print(A)
                A[retainedone,int(sizeA[retainedone]-1)]=A[cleanedone,it2]
        A[cleanedone,:]=np.zeros(A.shape[1]) #为了保持行号还是正确的，所以不删除行只是全部清除为0
        sizeA[cleanedone]=0
        A[np.where(A==cleanedone+1)]=retainedone+1#把别的点和被清除点的连线全都改掉
        print('switchedA'+str(A))
    return sizeA[np.where(sizeA!=0)][0]-1# size本身算了行号
    
def choose(A):
    i=random.randint(0, A.shape[0]-1)
    j=random.randint(1,A.shape[1]-1) #选的时候要跳过行号，否则就是自己和自己配对了
    while A[i,j]==0:
        i=random.randint(0, A.shape[0]-1)
        j=random.randint(1,A.shape[1]-1)
    return i,j


In [41]:
path='D:/onedrive/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/stanford-algs-master/stanford-algs-master/testCases/course1/assignment4MinCut'
os.chdir(path)
for txtname in os.listdir():
    if txtname=='input_random_2_6.txt':
        lenA=6
        A=np.zeros([lenA,int(lenA**2/2)])# *长度如果不够用,加满了会在26行报错，平方后一定是够用的，不过是分配的内存很大了
        sizeA=np.zeros([lenA,1])
        for i in range(lenA):
        #     print(i)
            B=np.array(pd.read_csv(txtname,header=None,sep=' ',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
#             B[0,-1]=0
#             print(B)
        # print(B.shape)
            sizeA[i]=B.shape[1]#这样读最后会多读出来一个0
            A[i,0:B.shape[1]]=B[0,:]
        C=copy.deepcopy(A)
        sizeC=copy.deepcopy(sizeA)
        A=copy.deepcopy(C)
        sizeA=copy.deepcopy(sizeC)
        minsize=contraction(A,sizeA)
        for i in range(1):
            A=copy.deepcopy(C)
            sizeA=copy.deepcopy(sizeC)
            size=contraction(A,sizeA)
            if minsize>size:
                minsize=size
        print(txtname+'calculated:'+str(minsize))
        txtname2='output'+txtname[5:]
#         txtname2[:5]=
        answer=np.loadtxt(path+'/'+txtname2)
        print(txtname2+'answer:'+str(answer))



[[1 2 3 4]]
[[2 1 3 6]]
[[3 2 4 1 5]]
[[4 3 1 5]]
[[5 4 3]]
[[6 2]]
[[1. 2. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 1. 3. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 2. 4. 1. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 3. 1. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 4. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [6. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
sizeA[[4.]
 [4.]
 [5.]
 [4.]
 [3.]
 [2.]]
newloop
cleanedone5
retainedone1
cleandedA
[[1. 2. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 1. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [3. 2. 4. 1. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 3. 1. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 4. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [6. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
sizeA[[4.]
 [3.]
 [5.]
 [4.]
 [3.]
 [2.]]
switchedA[[1. 2. 3. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 1. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

## output

In [68]:
path='D:/onedrive/OneDrive - tongji.edu.cn/knowledge management/expertise/projects_on the way/algorithms/'
lenA=200
A=np.zeros([lenA,int(lenA**2/2)],np.int32)# *10的长度只是预估的，有可能够用有可能不够用
sizeA=np.zeros([lenA,1])
for i in range(lenA):
#     print(i)
    B=np.array(pd.read_csv(path+'Programming Assignment #4.txt',header=None,sep='	',skiprows=list(range(0,i)),nrows=1))#每一行的数据长度不等，就只能一行行搞
    B[0,-1]=0
#     print(B)
# print(B.shape)
    sizeA[i]=B.shape[1]-1
    A[i,0:B.shape[1]-1]=B[0,:-1]
C=copy.deepcopy(A)
sizeC=copy.deepcopy(sizeA)
print(A)
np.savetxt('A.txt',A)

# print(sizeA)

[[  1  37  79 ...   0   0   0]
 [  2 123 134 ...   0   0   0]
 [  3  48 123 ...   0   0   0]
 ...
 [198  91  37 ...   0   0   0]
 [199 123 186 ...   0   0   0]
 [200 149 155 ...   0   0   0]]
[[25.]
 [24.]
 [27.]
 [27.]
 [22.]
 [22.]
 [22.]
 [28.]
 [22.]
 [26.]
 [22.]
 [27.]
 [35.]
 [21.]
 [30.]
 [28.]
 [29.]
 [26.]
 [22.]
 [25.]
 [28.]
 [28.]
 [21.]
 [26.]
 [25.]
 [23.]
 [26.]
 [27.]
 [27.]
 [22.]
 [22.]
 [30.]
 [22.]
 [21.]
 [23.]
 [32.]
 [35.]
 [22.]
 [32.]
 [21.]
 [32.]
 [25.]
 [29.]
 [23.]
 [26.]
 [22.]
 [29.]
 [29.]
 [21.]
 [25.]
 [21.]
 [32.]
 [30.]
 [21.]
 [23.]
 [31.]
 [22.]
 [32.]
 [21.]
 [25.]
 [21.]
 [30.]
 [23.]
 [22.]
 [26.]
 [24.]
 [21.]
 [27.]
 [23.]
 [21.]
 [27.]
 [25.]
 [29.]
 [23.]
 [31.]
 [31.]
 [28.]
 [24.]
 [33.]
 [35.]
 [26.]
 [28.]
 [21.]
 [28.]
 [23.]
 [28.]
 [29.]
 [25.]
 [24.]
 [24.]
 [32.]
 [27.]
 [21.]
 [21.]
 [26.]
 [23.]
 [21.]
 [27.]
 [27.]
 [24.]
 [27.]
 [28.]
 [25.]
 [26.]
 [23.]
 [21.]
 [32.]
 [31.]
 [36.]
 [25.]
 [26.]
 [23.]
 [29.]
 [27.]
 [21.]
 [3

In [69]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(1000):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    print(size)
    if minsize>size:
        minsize=size
minsize

17.0
24.0
21.0
24.0
20.0
20.0
20.0
20.0
27.0
22.0
22.0
22.0
21.0
26.0
28.0
33.0
25.0
21.0
20.0
26.0
23.0
23.0
21.0
20.0
20.0
20.0
23.0
20.0
22.0
28.0
20.0
26.0
20.0
27.0
22.0
20.0
22.0
20.0
22.0
25.0
26.0
22.0
20.0
20.0
46.0
24.0
21.0
20.0
29.0
22.0
22.0
20.0
21.0
24.0
22.0
43.0
23.0
24.0
26.0
20.0
20.0
26.0
21.0
20.0
23.0
20.0
24.0
20.0
23.0
21.0
20.0
17.0
22.0
25.0
20.0
25.0
26.0
46.0
22.0
24.0
22.0


KeyboardInterrupt: 

In [8]:
A=copy.deepcopy(C)
sizeA=copy.deepcopy(sizeC)
minsize=contraction(A,sizeA)
for i in range(9999):
    A=copy.deepcopy(C)
    sizeA=copy.deepcopy(sizeC)
    size=contraction(A,sizeA)
    print(size)
    if minsize>size:
        minsize=size
minsize

21.0
220.0
221.0
219.0
239.0
123.0
225.0
219.0
26.0
219.0
219.0
24.0
227.0
23.0
25.0
219.0
221.0
220.0
24.0
221.0
23.0
27.0
224.0
219.0
220.0
219.0
220.0
21.0
225.0
23.0
24.0
221.0
224.0
27.0
225.0
220.0
221.0
23.0
27.0
29.0
225.0
22.0
219.0
21.0
221.0
23.0
21.0
21.0
224.0
219.0
220.0
25.0
225.0
24.0
219.0
219.0
111.0
219.0
219.0
222.0
22.0
222.0
22.0
221.0
220.0
22.0
219.0
225.0
22.0
21.0
219.0
219.0
21.0
21.0
223.0
221.0
21.0
219.0
221.0
223.0
23.0
222.0
225.0
23.0
24.0
225.0
22.0
21.0
219.0
22.0
221.0
21.0
27.0
21.0
25.0
21.0
22.0
219.0
224.0
21.0
221.0
219.0
219.0
233.0
22.0
223.0
223.0
219.0
25.0
225.0
223.0
22.0
222.0
219.0
21.0
219.0
21.0
21.0
28.0
21.0
21.0
219.0
219.0
22.0
123.0
219.0
21.0
220.0
225.0
223.0
22.0
25.0
219.0
21.0
21.0
223.0
224.0
32.0
219.0
219.0
220.0
223.0
223.0
219.0
223.0
225.0
219.0
219.0
219.0
21.0
219.0
24.0
227.0
21.0
54.0
27.0
21.0
22.0
21.0
219.0
22.0
21.0
21.0
219.0
219.0
222.0
227.0
219.0
219.0
227.0
220.0
23.0
25.0
26.0
22.0
22.0
219.0
226.0
41.0
22

219.0
219.0
233.0
223.0
21.0
223.0
219.0
22.0
227.0
21.0
219.0
219.0
226.0
21.0
21.0
123.0
23.0
26.0
222.0
221.0
23.0
23.0
222.0
221.0
219.0
29.0
225.0
219.0
219.0
21.0
222.0
221.0
21.0
31.0
21.0
21.0
219.0
223.0
221.0
225.0
222.0
23.0
22.0
221.0
220.0
22.0
23.0
22.0
25.0
27.0
219.0
21.0
221.0
26.0
41.0
23.0
22.0
226.0
227.0
23.0
26.0
21.0
21.0
21.0
219.0
22.0
32.0
26.0
22.0
229.0
220.0
221.0
22.0
223.0
219.0
219.0
23.0
21.0
226.0
225.0
219.0
23.0
29.0
219.0
219.0
220.0
222.0
219.0
232.0
229.0
224.0
219.0
22.0
220.0
221.0
220.0
221.0
222.0
221.0
22.0
21.0
220.0
21.0
219.0
23.0
28.0
219.0
236.0
27.0
224.0
24.0
23.0
27.0
22.0
22.0
26.0
23.0
21.0
220.0
23.0
22.0
219.0
230.0
244.0
21.0
25.0
25.0
22.0
220.0
222.0
221.0
221.0
219.0
23.0
221.0
25.0
219.0
25.0
21.0
29.0
219.0
219.0
24.0
22.0
221.0
219.0
24.0
224.0
23.0
243.0
221.0
26.0
21.0
229.0
26.0
25.0
21.0
220.0
22.0
225.0
21.0
21.0
30.0
22.0
22.0
225.0
227.0
123.0
25.0
22.0
222.0
21.0
224.0
21.0
25.0
23.0
219.0
35.0
22.0
24.0
229.0
221.0

21.0
220.0
225.0
26.0
25.0
227.0
26.0
111.0
224.0
22.0
123.0
23.0
21.0
22.0
28.0
233.0
219.0
21.0
25.0
23.0
78.0
22.0
30.0
27.0
219.0
22.0
21.0
25.0
220.0
28.0
21.0
27.0
224.0
220.0
23.0
224.0
23.0
29.0
21.0
220.0
22.0
220.0
220.0
22.0
22.0
22.0
21.0
22.0
44.0
23.0
221.0
219.0
223.0
221.0
219.0
221.0
21.0
219.0
25.0
33.0
226.0
219.0
224.0
22.0
223.0
223.0
222.0
22.0
223.0
26.0
28.0
22.0
30.0
25.0
224.0
28.0
22.0
22.0
21.0
222.0
30.0
26.0
220.0
21.0
219.0
22.0
219.0
222.0
21.0
22.0
23.0
22.0
223.0
225.0
22.0
26.0
221.0
27.0
229.0
26.0
21.0
23.0
221.0
220.0
221.0
219.0
22.0
227.0
219.0
24.0
223.0
223.0
225.0
23.0
21.0
221.0
26.0
22.0
219.0
23.0
221.0
22.0
219.0
219.0
221.0
222.0
219.0
24.0
219.0
21.0
219.0
221.0
221.0
221.0
227.0
27.0
21.0
22.0
23.0
22.0
221.0
219.0
221.0
221.0
219.0
27.0
229.0
219.0
219.0
28.0
223.0
25.0
26.0
223.0
223.0
22.0
229.0
220.0
220.0
49.0
228.0
223.0
21.0
219.0
223.0
220.0
27.0
219.0
23.0
221.0
220.0
24.0
22.0
23.0
21.0
219.0
220.0
219.0
229.0
21.0
229.0
219.0

221.0
21.0
226.0
22.0
26.0
23.0
222.0
21.0
23.0
219.0
225.0
21.0
23.0
223.0
23.0
21.0
22.0
27.0
223.0
32.0
228.0
21.0
22.0
221.0
219.0
222.0
224.0
219.0
29.0
24.0
221.0
21.0
22.0
220.0
224.0
25.0
221.0
219.0
228.0
219.0
224.0
25.0
222.0
28.0
219.0
22.0
22.0
219.0
221.0
228.0
21.0
23.0
29.0
219.0
219.0
219.0
21.0
225.0
21.0
219.0
23.0
219.0
23.0
25.0
219.0
237.0
222.0
227.0
242.0
226.0
229.0
226.0
223.0
21.0
219.0
26.0
25.0
25.0
25.0
219.0
221.0
221.0
21.0
42.0
219.0
222.0
21.0
56.0
225.0
221.0
219.0
221.0
223.0
229.0
221.0
22.0
21.0
31.0
24.0
224.0
236.0
230.0
219.0
22.0
22.0
222.0
228.0
223.0
221.0
225.0
25.0
219.0
219.0
220.0
21.0
220.0
222.0
225.0
22.0
22.0
226.0
223.0
221.0
29.0
222.0
220.0
222.0
219.0
219.0
22.0
21.0
21.0
21.0
21.0
22.0
230.0
28.0
220.0
219.0
22.0
21.0
21.0
46.0
23.0
29.0
21.0
223.0
23.0
26.0
219.0
22.0
221.0
225.0
21.0
21.0
23.0
24.0
219.0
225.0
30.0
221.0
25.0
22.0
23.0
28.0
219.0
221.0
219.0
232.0
26.0
22.0
227.0
220.0
25.0
219.0
247.0
23.0
219.0
220.0
24.0
219

27.0
224.0
22.0
21.0
21.0
220.0
23.0
250.0
219.0
224.0
227.0
221.0
223.0
22.0
28.0
222.0
221.0
220.0
29.0
220.0
219.0
219.0
226.0
221.0
244.0
236.0
223.0
222.0
21.0
223.0
21.0
29.0
224.0
224.0
66.0
24.0
24.0
22.0
230.0
219.0
23.0
219.0
111.0
221.0
22.0
26.0
22.0
22.0
25.0
223.0
49.0
221.0
221.0
47.0
25.0
21.0
219.0
23.0
219.0
223.0
26.0
41.0
220.0
223.0
25.0
26.0
21.0
230.0
220.0
220.0
25.0
22.0
220.0
27.0
31.0
24.0
22.0
26.0
237.0
33.0
221.0
25.0
21.0
23.0
44.0
22.0
225.0
225.0
220.0
225.0
222.0
26.0
27.0
21.0
27.0
21.0
21.0
24.0
228.0
219.0
219.0
222.0
219.0
221.0
27.0
21.0
219.0
219.0
23.0
23.0
123.0
22.0
23.0
25.0
22.0
227.0
21.0
219.0
23.0
223.0
238.0
220.0
21.0
220.0
21.0
24.0
22.0
22.0
224.0
29.0
23.0
22.0
225.0
21.0
226.0
225.0
222.0
219.0
227.0
26.0
221.0
220.0
23.0
22.0
222.0
225.0
27.0
225.0
219.0
21.0
223.0
222.0
219.0
25.0
21.0
219.0
22.0
23.0
225.0
25.0
25.0
22.0
223.0
21.0
25.0
22.0
221.0
25.0
28.0
23.0
219.0
221.0
219.0
26.0
24.0
225.0
219.0
220.0
25.0
123.0
26.0
231.0


26.0
21.0
26.0
219.0
225.0
21.0
219.0
225.0
221.0
219.0
24.0
25.0
26.0
246.0
245.0
21.0
21.0
22.0
232.0
22.0
21.0
26.0
27.0
224.0
21.0
23.0
111.0
219.0
219.0
224.0
21.0
22.0
23.0
23.0
221.0
219.0
219.0
221.0
25.0
27.0
225.0
24.0
221.0
230.0
21.0
220.0
219.0
219.0
22.0
21.0
23.0
21.0
28.0
229.0
24.0
27.0
22.0
21.0
21.0
220.0
222.0
228.0
21.0
35.0
25.0
229.0
32.0
24.0
24.0
25.0
223.0
25.0
24.0
219.0
219.0
24.0
219.0
21.0
221.0
21.0
221.0
219.0
25.0
26.0
219.0
123.0
221.0
123.0
219.0
231.0
219.0
219.0
25.0
219.0
220.0
21.0
28.0
225.0
221.0
28.0
227.0
21.0
219.0
221.0
227.0
23.0
21.0
229.0
241.0
219.0
223.0
221.0
219.0
220.0
220.0
28.0
31.0
221.0
219.0
224.0
219.0
23.0
219.0
24.0
27.0
21.0
219.0
25.0
25.0
21.0
25.0
229.0
25.0
231.0
219.0
219.0
225.0
222.0
22.0
27.0
224.0
21.0
22.0
28.0
24.0
24.0
223.0
22.0
227.0
221.0
220.0
223.0
219.0
27.0
219.0
22.0
22.0
225.0
24.0
221.0
223.0
22.0
219.0
229.0
221.0
219.0
219.0
219.0
30.0
22.0
227.0
23.0
22.0
46.0
21.0
230.0
25.0
27.0
26.0
22.0
21.0
225.

23.0
25.0
243.0
219.0
221.0
225.0
223.0
27.0
26.0
222.0
25.0
22.0
25.0
219.0
227.0
32.0
219.0
219.0
25.0
229.0
28.0
222.0
219.0
24.0
23.0
23.0
220.0
21.0
219.0
21.0
23.0
220.0
219.0
22.0
22.0
21.0
23.0
21.0
27.0
22.0
219.0
27.0
224.0
22.0
230.0
22.0
219.0
219.0
219.0
111.0
25.0
219.0
221.0
28.0
22.0
25.0
23.0
22.0
26.0
23.0
225.0
35.0
221.0
25.0
27.0
26.0
27.0
227.0
219.0
231.0
219.0
230.0
221.0
229.0
27.0
222.0
223.0
23.0
32.0
222.0
221.0
21.0
40.0
223.0
242.0
219.0
25.0
27.0
23.0
223.0
41.0
222.0
226.0
22.0
21.0
23.0
225.0
22.0
219.0
25.0
219.0
22.0
219.0
219.0
220.0
25.0
21.0
22.0
223.0
219.0
229.0
22.0
219.0
35.0
219.0
219.0
220.0
222.0
21.0
220.0
221.0
223.0
25.0
219.0
26.0
219.0
224.0
225.0
21.0
219.0
27.0
219.0
220.0
22.0
23.0
21.0
22.0
221.0
219.0
27.0
21.0
224.0
21.0
23.0
21.0
220.0
230.0
25.0
25.0
21.0
21.0
219.0
219.0
28.0
26.0
225.0
22.0
221.0
22.0
219.0
221.0
23.0
21.0
221.0
21.0
226.0
220.0
111.0
221.0
23.0
22.0
225.0
22.0
219.0
25.0
220.0
27.0
26.0
219.0
25.0
219.0
233.0

21.0

In [9]:
minsize

21.0